<div class="w-screen overflow-hidden">
    <!-- 首屏部分 -->
    <div class="relative">
        <img src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_landing_bg.png'); ?>" class="w-screen" />
        <div class="absolute top-0 left-0 text-white w-full my-14">
            <div class="w-4/5 mx-auto">
                <img src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_logo.png') ?>" alt="" class="inline-block w-28 h-12 mr-80">
                <nav class="inline-block text-xl">
                    <span class="m-7">HOME</span>
                    <span class="m-7">BUILD</span>
                    <span class="m-7">ENVIRONMENTS</span>
                    <span class="m-7">PRODUCTS</span>
                    <span class="m-7">ABOUT THE SYSTEM</span>
                    <span class="m-7">SIGN UP/LOG IN</span>
                </nav>
                <span class="inline-block float-right"><img src="<?php echo $this->getViewFileUrl('Tti_Packout::images/search_icon.png') ?>" class="inline-block w-6 h-outo ml-24"><img src="<?php echo $this->getViewFileUrl('Tti_Packout::images/cart_icon.png') ?>" class="inline-block w-6 h-outo ml-24" alt=""></span>
                <div class="h-80"></div>
                <img class="w-4/12 h-auto mt-60" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/text_headline.png') ?>" alt="">
                <div class="hover:bg-red-700 w-96"><img class="w-96 h-auto mt-32" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_build_now.png') ?>" alt=""></div>
                <div class="h-96"></div>
                <div class="h-10"></div>
                <img class="m-auto w-2/3" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/text_experience.png') ?>" alt="">
            </div>
        </div>
    </div>
    <!-- 场景部分 -->
    <div class="relative">
        <div class="bg-image">
            <img src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_environment_site.png'); ?>" class="w-screen card-site" />
            <img src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_environment_transit.png'); ?>" class="w-screen hidden card-transit" />
            <img src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_environment_site.png'); ?>" class="w-screen hidden card-shop" />
        </div>
        <div class="absolute bottom-52 -right-32 w-1/2">
            <div class="image-list">
                <div>
                    <img class="" data-image="card-shop" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_shop.png'); ?>" alt="">
                </div>
                <div>
                    <img class="" data-image="card-site" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_site.png'); ?>" alt="">
                </div>
                <div>
                    <img class="" data-image="card-transit" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_transit.png'); ?>" alt="">
                </div>
                <div>
                    <img class="" data-image="card-shop" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_shop.png'); ?>" alt="">
                </div>
                <div>
                    <img class="" data-image="card-site" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_site.png'); ?>" alt="">
                </div>
            </div>
        </div>
        <div class="absolute top-1/3 pt-32 left-64 text-white">
            <span class="text-5xl">PACKOUT System in</span><br/>
            <span class="inline-block text-10xl helveticaNeue-93 my-10">SITE</span><br/>
            <span class="inline-block text-sm font-light leading-loose">Lorem ipsum dolor sit amet,consecteture adipicing elit,sed diam nonummy nibh euismod tincidunt ut<br/>laoreet dolore magna aliquam erat volutpat.Ut wisi enim ad minim</span>
        </div>
        <div class="hover:bg-red-700 w-96 absolute bottom-80 left-64"><img class="w-96 h-auto" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_build_now.png') ?>" alt=""></div>
        <div class="absolute bottom-32 right-72">
            <img class="inline-block w-16 mr-8 ml-6 pre-arrow" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_left_arrow.png'); ?>" alt="">
            <img class="inline-block w-16 mr-8 next-arrow" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_right_arrow.png'); ?>" alt="">
            <span class="text-white text-2xl font-extrabold mr-6">01</span>
            <!-- <span class="inline-block border-t-4 border-white w-32 align-middle line-card-shop"></span><span class="inline-block border-t border-white w-32 align-middle line-card-site"></span><span class="inline-block border-t border-white w-32 align-middle line-card-transit"></span> -->
            <div class="inline-block"><span class="inline-block border-t border-gray-200 rounded-md w-96 float-left align-middle "></span><span class="transition  duration-500 ease-in-out inline-block border-b-4 border-white transition w-1/3 align-middle float-left bold-line relative -top-1"></span></div>
            <span class="text-white text-2xl font-extrabold ml-6">03</span>
        </div>
    </div>
    <!-- 产品部分 -->
    <div class="flex flex-col">
        <div class="pt-32 pb-6 pl-48 ">
            <span class="text-5xl helveticaNeue-93 leading-normal inline-block mr-44">PACKOUT <span class="align-sup">TM</span></br>Large Tool Box</span><span class="text-sm">Categories:PACKOUT <small class="align-sup">TM</small>,Tool Box</span></br><span>48-22-8425</span>
        </div>
        <div class="flex w-full">
            <div class="flex flex-col w-24 ml-24 mt-12">
                <img class="w-24 mb-8" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_add_to_fravorite.png'); ?>" alt="">
                <img class="w-6 mx-auto" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/text_add_to_fravorite.png'); ?>" alt="">
            </div>
            <div class="w-1/2 p-10">
                <div class="slider product-slider-for w-full h-104">
                    <div>
                        <div class="flex items-center h-106">
                            <img class="w-full m-auto" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_product_image.png'); ?>" alt="">
                        </div>
                    </div>
                    <div>
                        <div class="flex items-center h-106">
                            <img class="w-96 m-auto" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_product_gallery_icon_2.png'); ?>" alt="">
                        </div>
                    </div>
                    <div>
                        <div class="flex items-center h-106">
                            <img class="w-96 m-auto" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_product_gallery_icon_3.png'); ?>" alt="">
                        </div>
                    </div>
                    <div>
                        <div class="flex items-center h-106">
                            <img class="w-96 m-auto" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_product_gallery_icon_3.png'); ?>" alt="">
                        </div>
                    </div>
                </div>
                <div class="flex items-center">
                    <div>
                        <img class="w-16 button-left-gray-arrow" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_left_gray_arrow.png'); ?>" alt="">
                    </div>
                    <div class="slider product-slider-nav p-10 w-4/5">
                        <div>
                            <div class="h-52 flex items-center">
                                <img class="w-2/3 m-auto" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_product_gallery_icon_1.png'); ?>" alt="">
                            </div>
                        </div>
                        <div>
                            <div class="h-52 flex items-center">
                                <img class="w-2/3 m-auto" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_product_gallery_icon_2.png'); ?>" alt="">
                            </div>
                        </div>
                        <div>
                            <div class="h-52 flex items-center">
                                <img class="w-2/3 m-auto" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_product_gallery_icon_3.png'); ?>" alt="">
                            </div>
                        </div>
                        <div>
                            <div class="h-52 flex items-center">
                                <img class="w-2/3 m-auto" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_product_gallery_icon_3.png'); ?>" alt="">
                            </div>
                        </div>
                    </div>
                    <div>
                        <img class="w-16 button-right-gray-arrow" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_right_gray_arrow.png'); ?>" alt="">
                    </div>
                </div>
            </div>
            <div>
                <img class="w-3/5" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/text_product_description.png'); ?>" alt="">
                <img class="w-1/4 mt-32" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_learn_more.png'); ?>" alt="">
            </div>
        </div>
        <div class="bg-gray-200">
            <div class="flex items-center h-28 w-full bg-white border border-gray-200">
                <div class="w-44 bg-gray-200">
                    <img class="h-28 drop_down_menu" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_drop_down_menu.png'); ?>" alt="">
                </div>
                <nav class="h-28 items-center text-center text-gray-400 text-base product-category">
                    <div class="inline-block pt-12 px-7 h-full text-red-700 border-t-2 border-red-700">Tool Boxes</div>
                    <div class="inline-block pt-12 px-7 h-full">Rolling Storage</div>
                    <div class="inline-block pt-12 px-7 h-full">Orgnizers</div>
                    <div class="inline-block pt-12 px-7 h-full">Coolers</div>
                    <div class="inline-block pt-12 px-7 h-full">Mounting</div>
                </nav>
                <div>
                    <span class="inline-block h-0.5 w-72 bg-gray-300"></span>
                </div>
                <div>
                    <img class="w-72 ml-20" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_red_build_now.png'); ?>" alt="">
                </div>
            </div>
            <div class="overflow-hidden transition-all duration-1000 h-0 product_card">
                <div class="flex">
                    <div class="w-44 flex-shrink-0"></div>
                    <div class="w-full">
                        <div class="w-full py-32 space-x-32 card_product_items">
                            <div>
                                <img class="w-102" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_product.png'); ?>" alt="">
                            </div>
                            <div>
                                <img class="w-102" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_product.png'); ?>" alt="">
                            </div>
                            <div>
                                <img class="w-102" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_product.png'); ?>" alt="">
                            </div>
                            <div>
                                <img class="w-102" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_product.png'); ?>" alt="">
                            </div>
                            <div>
                                <img class="w-102" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_product.png'); ?>" alt="">
                            </div>
                            <div>
                                <img class="w-102" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_product.png'); ?>" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <div>
                    <div class="flex">
                        <div class="w-44"></div>
                        <div class="flex flex-row flex-grow pb-32 pl-10 pr-32 items-center justify-between">
                            <div>
                                <img class="inline-block w-16 mr-8 drop_menu_left_arrow" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_drop_menu_left_arrow.png'); ?>" alt="">
                                <img class="inline-block w-16 drop_menu_right_arrow" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_drop_menu_right_arrow.png'); ?>" alt="">
                            </div>
                            <div>
                                <div class="flex items-center inline-block border-t border-gray-400 w-80 h-0">
                                    <div class="inline-block border-t-4 border-gray-900 w-1/5 h-0 drop-progress-line"></div>
                                </div>
                            </div>
                            <div>
                                <img class="w-20" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_see_all.png'); ?>" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- fmailyshot section -->
    <div>
        <div class="relative">
            <div>
                <img class="w-full" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/image_familyshot.png'); ?>" alt="">
            </div>
            <div class="p-2 w-72 h-98 absolute top-10 left-1/2">
                <div class="relative w-full h-full product_details">
                    <img class="absolute h-0 w-full bottom-0 left-0 " src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_product_details.png'); ?>" alt="">
                </div>
                <div class="w-20 relative m-auto -top-10 button_product_details">
                    <img class="product_details_image" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_product_details.png'); ?>" alt="">
                    <img class="product_details_close_image transition duration-1000 transform rotate-45 hidden" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_product_details_close.png'); ?>" alt="">
                </div>
            </div>
            <div class="p-2 w-72 h-98 absolute top-14 left-1/3">
                <div class="relative w-full h-full product_details">
                    <img class="absolute h-0 w-full bottom-0 left-0 " src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_product_details.png'); ?>" alt="">
                </div>
                <div class="w-20 relative m-auto -top-10 button_product_details">
                    <img class="product_details_image" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_product_details.png'); ?>" alt="">
                    <img class="product_details_close_image transition duration-1000 transform rotate-45 hidden" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_product_details_close.png'); ?>" alt="">
                </div>
            </div>
            <div class="p-2 w-72 h-98 absolute top-96 left-12">
                <div class="relative w-full h-full product_details">
                    <img class="absolute h-0 w-full bottom-0 left-0 " src="<?php echo $this->getViewFileUrl('Tti_Packout::images/card_product_details.png'); ?>" alt="">
                </div>
                <div class="w-20 relative m-auto -top-10 button_product_details">
                    <img class="product_details_image" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_product_details.png'); ?>" alt="">
                    <img class="product_details_close_image transition duration-1000 transform rotate-45 hidden" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_product_details_close.png'); ?>" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- share setction -->
    <div class="mb-44">
        <div class="mt-44">
            <img class="w-1/2 mx-auto" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/text_title.png'); ?>" alt="">
        </div>
        <div></div>
        <div>
            <img class="w-52 mx-auto" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_see_more.png'); ?>" alt="">
        </div>
        <footer class="px-32">
            <div class="float-left">
                <span class="text-2xl">©️2021 All rights reserved</span>
            </div>
            <div class="inline-block float-right space-x-12">
                <img class="inline-block w-3" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_social_media_icon_1.png'); ?>" alt="">
                <img class="inline-block w-6" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_social_media_icon_2.png'); ?>" alt="">
                <img class="inline-block w-6" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_social_media_icon_3.png'); ?>" alt="">
                <img class="inline-block w-6" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_social_media_icon_4.png'); ?>" alt="">
                <img class="inline-block w-6" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_social_media_icon_5.png'); ?>" alt="">
                <img class="inline-block w-6" src="<?php echo $this->getViewFileUrl('Tti_Packout::images/button_social_media_icon_6.png'); ?>" alt="">
            </div>
        </footer>
    </div>
</div>